TaskarCenterAtUW/TDEI-ExternalAPIs

- tdei-api-gateway.json
Reference changes from org to project group.
> Feature auth changes

- tdei-api-gateway.json
> type change

- .github/workflows/generaet_api_client.yml
- .github/workflows/generate_api_client.yml
Added workflow to trigger api client generation
> Feature 466

- tdei-api-gateway.json
Feature usecase 1 ,2, 3, 4, 12 changes updated
> Feature usecase 1 2 3 4 12

- README.md
minor change to trigger the api-client
> minor change to trigger the api-client

- README.md
minor change , reverting to trigger the api client
> minor change , reverting to trigger the api client

- README.md
minor changes to trigger the build
> minor changes to trigger the build

- README.md
minor change to trigger the workflow
> minor change to trigger the workflow

- tdei-api-gateway.json
> invalidate use case changes

- tdei-api-gateway.json
adding schema string to generate the client code properly
> adding schema string

- tdei-api-gateway.json
> enum correction

- tdei-api-gateway.json
> invalid prop

- tdei-api-gateway.json
added metadata filters for osw GET call
Renamed param date_time to valid_to
> metadata filters

- tdei-api-gateway.json
Added missing prop collection_method and enums
> Feature meta filters

- tdei-api-gateway.json
/dataset-flattern/:tdei_record_id - [On-demand flattening of data]
/dataset-flattern/status/:job_id - [status of on-demand flattening of data]
/dataset-bbox - [dataset bbox use case query]
/dataset-bbox/status/:job_id - [dataset bbox status]
/dataset-bbox/download/:job_id - [dataset bbox download]
> backend apis

- tdei-api-gateway.json
Datasetbbox query mandatory query fields
Added missing override query
> required params

- tdei-api-gateway.json
> query parameter

- .github/workflows/generate_api_client.yml
- tdei-api-gateway.json
Merging from gs implementation branch to DEV branch
> Gs api gateway implementation

- tdei-api-gateway.json
Flex
/api/v1/gtfs-flex
/api/v1/gtfs-flex/upload/{tdei_project_group_id}/{tdei_service_id}
/api/v1/gtfs-flex/publish/{tdei_dataset_id}
/api/v1/gtfs-flex/validate
/api/v1/gtfs-flex/{tdei_dataset_id}
/api/v1/gtfs-flex/versions
Pathways
/api/v1/gtfs-pathways
/api/v1/gtfs-pathways/upload/{tdei_project_group_id}/{tdei_service_id}
/api/v1/gtfs-pathways/publish/{tdei_dataset_id}
/api/v1/gtfs-pathways/validate
/api/v1/gtfs-pathways/{tdei_dataset_id}
/api/v1/gtfs-pathways/versions
> flex pathways unification

- tdei-api-gateway.json
> secondary gateway

- tdei-api-gateway.json
> gateway url change

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
> 907, 908, 909

- tdei-api-gateway.json
enhanced groups/services filter
> enhanced groups/services filter

- tdei-api-gateway.json
**Task**:
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/873/  
**New api** 
/api/v1/osw/dataset-tag-road
**Modifed API**
/osw/{dataset-id} , accepts file_version as param. Enum values original | latest (default)
> dataset road tag

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
fix for https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/936
> updated url for TDEI website, and the email to contact

- tdei-api-gateway.json
fix for 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/950/
> service all option

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
description correction for osw download endpoint
> description correction

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Added default status filter to all for dataset endpoint
> default status all for datasets

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Implementation
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/860/
> Feature 860

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
- tdei-api.json
977 changes to /dataset api response . Added project_group and service object. 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/977/
> Feature 977

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/995/
> Feature 995

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/994/ 
Added endpoint for clone dataset
> clone dataset feature

- tdei-api-gateway.json
- Linked to task [Task 990](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/990): Feature 3.1 – Improve messaging from job status, especially for long-running jobs.
- Job progress details are added.
> Feature job progress

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/997/
1. Spatial endpoint
2. Job status response object added to stage file
> spatial join enpoint changes

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Description and enum sequence changes
> Feature spatial join

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Added path for quality metric
- Reference task [Task 993](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/993): Feature 5.1 – TDEICore: Element Quality Metric: Write library
> added quality metric path

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Spatial join Spec correction for correct client generation. 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/997
> spec correction for client generation

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
- Adds quality metric calculation route
- Adds spatial join query route
- Enhances the job status response
> Dev and Stage sync

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Spec correction to allow API key access to tag quality & spatial join endpoint
> allow API key access to tag quality & spatial join endpoint

- tdei-api-gateway-stage.json
- tdei-api-gateway.json
1. correction in  Job list response properties
2. Removing unused Job type enum
> correction in properties

- .github/workflows/generate_api_client.yml
- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
1. Spatial join implementation
2. Job list response changes
> Dev to Stage Merge

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Extension change for changeset from .txt to .zip
> extension change

- .github/workflows/generate_api_client.yml
- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Changeset extension change from .txt to .zip
> Dev to stage

- .github/workflows/generate_api_client.yml
- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
> Stage to prod

- tdei-api-gateway.json
**Task** 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1220
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1250/
Added two new API for system and data metrics
> dataset metrics api changes

- tdei-api-gateway.json
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1243/
Added password recovery endpoint
> Recover password endpoint

- tdei-api-gateway.json
Task : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1243/
Added verify email endpoint.
> verify email

- tdei-api-gateway.json
- Added `/api/v1/osw/dataset-inclination/{tdei_dataset_id}` API details
> Added incline API

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task : 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1342
Added sorting and filtering to dataset endpoint
> Sorting & Filtering dataset

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
Task :
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1348
Updated the stage and prof spec with ixn changes from dev spec.
> ixn api to stage and prod spec

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1067/
1. Union api implementation
2. Added missing incline job to stage and prod spec
> 1067 changes

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1224/
API swagger document improvement
> External API improvement changes

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
1. Property change from  key_limitations_of_the_dataset to key_limitations
2. Added release_notes as filter
> dataset Key name change

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Updated spatial and join description
> Bugfix 1348

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
- Add ABANDONED state to Jobs
- This change adds the  `ABANDONED` filter to the job status
> Added ABANDONED state to Job status

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1558/
- Added proximity parameter to union job
> union proximity param

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1502/
- Spatial join will have new source dimension 'extension' to query and pull information from non standard files.
> spatial join extension changes

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2218/
- Updated project group schema properties
- Added new api routes 
- POST feedback
- GET feedback
- GET feedback metadata
- POST dataset dataviewer visibility
- Test the new apis working as expected
> Feature 2218

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2218/
- Added data_viewer_allowed filter for [GET]  /datasets 
- Verify data_viewer_allowed filter
> data_viewer_allowed filter

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2325
-  New API to download the CSV file
- API Path GET -  `osw/dataset-viewer/feedbacks/download`
- API Response - CSV file as attachment
- TDEI Portal
- Added unit test cases
> Added few more params

- tdei-api-gateway-prod.json
- tdei-api-gateway-stage.json
- tdei-api-gateway.json
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2325
- allow feedback download API to stream CSV or GeoJSON
- convert feedback rows into GeoJSON feature collection
- set response headers based on requested format
- test coverage for new geojson option
- TDEI Portal
- Added unit test cases
> feat: add geojson feedback download option
